/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/ext/termstructures/averageoisratehelper.hpp>
#include <ql/ext/termstructures/basistwoswaphelper.hpp>
//#include <ql/ext/termstructures/blackinvertedvoltermstructure.hpp>
#include <ql/ext/termstructures/crossccybasisswaphelper.hpp>
#include <ql/ext/termstructures/crossccybasismtmresetswaphelper.hpp>
#include <ql/ext/termstructures/resetablecrosscurrencyswaphelper.hpp>
//#include <ql/ext/termstructures/dynamicblackvoltermstructure.hpp>
//#include <ql/ext/termstructures/dynamicswaptionvolmatrix.hpp>
//#include <ql/ext/termstructures/hazardspreadeddefaulttermstructure.hpp>
//#include <ql/ext/termstructures/interpolateddiscountcurve.hpp>
//#include <ql/ext/termstructures/interpolateddiscountcurve2.hpp>
#include <ql/ext/termstructures/oibasisswaphelper.hpp>
#include <ql/ext/termstructures/oiccbasisswaphelper.hpp>
//#include <ql/ext/termstructures/oisratehelper.hpp>
//#include <ql/ext/termstructures/staticallycorrectedyieldtermstructure.hpp>
#include <ql/ext/termstructures/tenorbasisswaphelper.hpp>
//#include <ql/ext/termstructures/blackvariancecurve3.hpp>
//#include <ql/ext/termstructures/datedstrippedoptionlet.hpp>
//#include <ql/ext/termstructures/datedstrippedoptionletadapter.hpp>
//#include <ql/ext/termstructures/datedstrippedoptionletbase.hpp>
//#include <ql/ext/termstructures/dynamicoptionletvolatilitystructure.hpp>
//#include <ql/ext/termstructures/dynamicstype.hpp>
//#include <ql/ext/termstructures/optionletstripper1.hpp>
//#include <ql/ext/termstructures/optionletstripper2.hpp>
//#include <ql/ext/termstructures/spreadedoptionletvolatility.hpp>
//#include <ql/ext/termstructures/spreadedsmilesection.hpp>
//#include <ql/ext/termstructures/spreadedswaptionvolatility.hpp>
//#include <ql/ext/termstructures/strippedoptionletadapter2.hpp>
//#include <ql/ext/termstructures/swaptionvolatilityconverter.hpp>
#include <ql/ext/termstructures/subperiodsswaphelper.hpp>

