/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/ext/cashflows/averageonindexedcoupon.hpp>
#include <ql/ext/cashflows/averageonindexedcouponpricer.hpp>
#include <ql/ext/cashflows/couponpricer_ext.hpp>
#include <ql/ext/cashflows/subperiodscoupon.hpp>
#include <ql/ext/cashflows/subperiodscouponpricer.hpp>
#include <ql/ext/cashflows/fxlinkedcashflow.hpp>
#include <ql/ext/cashflows/floatingratefxlinkednotionalcoupon.hpp>
