/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/ext/instruments/averageois.hpp>
#include <ql/ext/instruments/crossccybasismtmresetswap.hpp>
#include <ql/ext/instruments/crossccybasisswap.hpp>
#include <ql/ext/instruments/crossccyswap.hpp>
#include <ql/ext/instruments/currencyswap.hpp>
#include <ql/ext/instruments/fxforward.hpp>
#include <ql/ext/instruments/makeaverageois.hpp>
#include <ql/ext/instruments/oibasisswap.hpp>
#include <ql/ext/instruments/oiccbasisswap.hpp>
#include <ql/ext/instruments/tenorbasisswap.hpp>
#include <ql/ext/instruments/subperiodsswap.hpp>
