/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

//#include <ql/ext/pricingengines/analyticcclgmfxoptionengine.hpp>
//#include <ql/ext/pricingengines/analyticlgmswaptionengine.hpp>
#include <ql/ext/pricingengines/crossccyswapengine.hpp>
#include <ql/ext/pricingengines/discountingcurrencyswapengine.hpp>
#include <ql/ext/pricingengines/discountingfxforwardengine.hpp>
#include <ql/ext/pricingengines/discountingswapenginemulticurve.hpp>
#include <ql/ext/pricingengines/oiccbasisswapengine.hpp>
//#include <ql/ext/pricingengines/numericlgmswaptionengine.hpp>
