/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

//#include <ql/ext/indexes/genericiborindex.hpp>
#include <ql/ext/indexes/fxindex.hpp>

//#include <ql/ext/indexes/ibor/all.hpp>
