/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/ext/cashflows/all.hpp>
#include <ql/ext/indexes/all.hpp>
#include <ql/ext/instruments/all.hpp>
#include <ql/ext/pricingengines/all.hpp>
#include <ql/ext/termstructures/all.hpp>
